-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceSaferEdit/maintenance/db/sql/bs_saferedit.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_saferedit (
  se_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  se_user_name VARCHAR(255) NOT NULL,
  se_page_title VARBINARY(255) NOT NULL,
  se_page_namespace INT DEFAULT 0 NOT NULL,
  se_edit_section INT DEFAULT -1 NOT NULL,
  se_timestamp BINARY(14) NOT NULL,
  PRIMARY KEY(se_id)
) /*$wgDBTableOptions*/;
